// Configuration for the deuro TSS bridge PoC
// Each party loads this config and uses PARTY_ID env var to identify itself

import { readFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data');

// Load party keys if they exist (generated by keygen.js)
function loadPartyKeys() {
  const keysPath = join(DATA_DIR, 'party-keys.json');
  if (!existsSync(keysPath)) return null;
  return JSON.parse(readFileSync(keysPath, 'utf8'));
}

const partyKeys = loadPartyKeys();

export const config = {
  // Party identification
  partyId: parseInt(process.env.PARTY_ID ?? '0'),
  totalParties: 3,
  threshold: 2, // 2-of-3

  // Party network addresses (each party runs on a different port)
  parties: [
    { id: 0, host: process.env.PARTY_0_HOST ?? 'http://localhost:4000', name: 'Party A' },
    { id: 1, host: process.env.PARTY_1_HOST ?? 'http://localhost:4001', name: 'Party B' },
    { id: 2, host: process.env.PARTY_2_HOST ?? 'http://localhost:4002', name: 'Party C' },
  ],

  // Party ECDSA keys (loaded from keygen output)
  partyKeys,

  // EVM configuration (Sepolia testnet)
  // Confirmation requirements match Bridgeless production:
  // https://rpc-api.node0.mainnet.bridgeless.com/cosmos/bridge/chains
  evm: {
    rpc: process.env.EVM_RPC ?? 'https://rpc.sepolia.org',
    chainId: 11155111,
    bridgeAddress: process.env.BRIDGE_ADDRESS ?? '',
    deuroToken: process.env.DEURO_TOKEN ?? '',
    confirmations: 64, // Bridgeless production: 64 blocks for Ethereum (~13 min)
    pollInterval: 15_000, // 15 seconds
  },

  // Zano configuration (testnet)
  zano: {
    daemonRpc: process.env.ZANO_DAEMON_RPC ?? 'http://127.0.0.1:11211/json_rpc',
    walletRpc: process.env.ZANO_WALLET_RPC ?? 'http://127.0.0.1:11212/json_rpc',
    confirmations: 10,
    assetId: process.env.ZANO_ASSET_ID ?? '',
    pollInterval: 30_000, // 30 seconds
  },

  // Session timing
  session: {
    intervalMs: 60_000,       // New signing session every 60 seconds
    consensusTimeoutMs: 10_000,  // 10 seconds for consensus
    signingTimeoutMs: 15_000,    // 15 seconds for signing
  },

  // Token mapping: Zano asset ID -> EVM token address
  // Allows the bridge to look up the correct EVM token for a Zano asset
  tokenMapping: process.env.ZANO_ASSET_ID && process.env.DEURO_TOKEN
    ? { [process.env.ZANO_ASSET_ID]: process.env.DEURO_TOKEN }
    : {},

  // Data directory
  dataDir: DATA_DIR,
};
